### ISSUE TITLE
history, back-forward button does not fire

### ISSUE THREAD

**Issue by boralp** [jlantunez/webslides#4]
When you press back or forward button in the browser the slide number changes not the slides.

**Comment by jlantunez** [comment]
Thanks! We'll fix it as soon as we can.

**Comment by ramon-src** [comment]
Hi everyone, 

I'm working on this bug/feature!

```javascript

    /**
     *  Bind the event HashChange when the prev/next history button was clicked
     */
    jQuery(window).bind("hashchange", function () {
        if (hasHash()) {
            goToSlideIfSlideHashChange();
        }
    });

    function hasHash(){
        return window.location.hash ? true : false;
    }

    function goToSlideIfSlideHashChange() {
        var paramsArr = getArrayOfHashParams();
        var slideObj = $.grep(paramsArr, function (e) {
            return (e.key == "slide");
        });
        if (slideObj.length == 1) {
            goToSlide(slideObj[0].value);
        }
    }

    function getArrayOfHashParams() {
        var hash = window.location.hash.replace('#', '').split('&');
        var paramsArr = new Array();
        for (var i = 0; i < hash.length; i++) {
            var itemArray = hash[i].split('=');
            var action = new Object();
            action.key = itemArray[0];
            action.value = itemArray[1];
            paramsArr.push(action);
        }
        return paramsArr;
    }
```

Everything is ok when I click on prev or next history button of chrome and the
URL has #slide = [number], the event listen and use the function goToSlide.

BUT, when we back to the first step like the First Site visit situation, where the URL doesn't
has hash slide. The event listener doesn't is activate because he is only if hash is changed.
Does anyone have any ideas for doing this part?

Other thing... What pattern should I adopt in the functions created above?

**Comment by ramon-src** [comment]
Please, tell me yours ide configurations... I used auto-indent... And my indentation rules differ from yours ><

**Comment by jlantunez** [comment]
Hi Ramon, 

I prefer use 2 spaces :)
