### ISSUE TITLE
Company logo on each slide / header

### ISSUE THREAD

**Issue by mokry** [jlantunez/webslides#57]
Hi,
Is there any possibility to add a global header on each slide? For the presentation I want to add logo and footer information to each slide globally.

**Comment by jlantunez** [comment]
Hi Michal, it is possible.

- Please download this zip file again: https://webslides.tv/webslides-latest.zip
- Go to /static/css/base.css: Remove "opacity: 0" header[role=banner] (line 1259)
- Add a footer outside of the <main> element

![webslides-header-footer1](https://cloud.githubusercontent.com/assets/2033183/23893308/39ee7fc8-089e-11e7-9642-cea5cf3f5fd9.png)
![webslides-header-footer-slide](https://cloud.githubusercontent.com/assets/2033183/23893378/7816ae92-089e-11e7-9122-1586949db18f.png)

**Comment by eddy-ojb** [comment]
Hello,

Although this solution adds a header, I see from inspecting the elements that the article still takes the whole page. How does one set it so that the "article" and "section" elements starts below the banner instead of ignoring the nav header? 

This is the best looking web-based slide show on the internet btw. Thank you so much jlantunez et al. it is opening some doors for my creativity.

**Comment by jlantunez** [comment]
Hi @eddy-ojb,

just change the `header` position to `relative`.
